### ISSUE TITLE
Code review on capstone project

### ISSUE THREAD

**Issue by niicode** [niicode/javascript-group-capstone#41]
Below is a link to the GitHub repository for our capstone project:
[Capstone-Project](https://github.com/users/niicode/projects/2)

We are two people collaborating on this capstone project.

**Comment by leonardodiasb** [comment]
Hi @niicode,

Everything is looking great! Please, merge this branch :shipit:
Congratulations! 🎉

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

 - [OPTIONAL] Great cards assignment. You could leave every project card in a 'To Do' column so you can grab it from that column and the Kanban board can be more meaningful.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
